課題前半部分：ユーザログイン機能、プロフィール編集機能
Terunori/e-navigator pull request #1
Opened 2019-01-06 20:36 UTC by Terunori

やりたかったこと
---

- ユーザー登録、ログイン機能の追加
- 登録したユーザーのプロフィール編集機能の追加
- 編集したプロフィールが確認できるページ（マイページ）の追加
- Herokuへのデプロイ

やったこと
----

- Devise gem の導入
- トップページの追加
- メールアドレスとパスワードによる新規登録・ログイン機能の実装
- ログアウト機能の実装（devise gemによる）
- パスワード変更機能の実装（devise gemによる）
- プロフィール情報として名前、誕生日、性別、出身大学を登録・編集できるようにした
- プロフィールが確認できるマイページの追加、プロフィール登録後にリダイレクトするようにした
- Herokuへのデプロイ
  - https://e-navigator-terunori.herokuapp.com/

動作確認方法
---

- [ ] ユーザーを新規で作成する
  - test@test.com, teru@test.com, mail@test.comは使用済みなのでそれ以外で作成してください
- [ ] ログアウトし再度同じアカウントでログインする
- [ ] パスワード変更画面を表示しパスワードを変更する
- [ ] プロフィール編集画面を表示しプロフィールを編集する
- [ ] マイページへの遷移を確認する

その他
---

- branchを切らずに作業を始めてしまい、プルリクエストを作る少し前までmasterで進めてしまいました。そのためmasterがforkしてから少し編集した状態となっています。

2019-01-08 03:39 UTC, pokotyamu commented
見ます👀

2019-01-08 03:40 UTC, pokotyamu commented
プルリクエストのタイトルいいですね 👍 
「何をやったか」が分かりやすくていいと思います！

2019-01-08 03:44 UTC, pokotyamu commented
ただ、ブランチ名が `terunori` となっていたり、コミットメッセージがそのコミットと対応していなかったりしているのが気になりますね。

ブランチ名はプルリクエストのタイトルのように、そのブランチで何をしたかったのか？を書くようにしましょう。
また、コミットメッセージもやったことの単位で分けるといいと思いました！
例) `README` ではなく `README の更新` や `Heroku のマイグレーションについてREADME に追記`など。
その際 README の差分のみをコミットとして追加し、関係のない差分は別のコミットに分けるのがいいと思います！

2019-01-08 04:10 UTC, pokotyamu requested changes
@Terunori 不要なコメント、プログラムの最後の改行、 `gitignore` については修正してください。
大まかなロジックとしては問題ないと思うので、コミットの粒度に気をつけつつ修正よろしくおねがいします。

2019-01-08 04:10 UTC, pokotyamu commented on .gitignore
> +# End of https://www.gitignore.io/api/rubymine+all
RubyMine の設定についてこのプロジェクトの `gitignore` に含めてしまうのは良くないと思います。
他のプロジェクトでも設定することになると思うので、 `.gitignore_global` に設定してみるのはいかがでしょう？

2019-01-08 04:10 UTC, pokotyamu commented on Gemfile
> +# gem 'gretel'
不要な gem はコメントアウトでなく、完全に削除してしまった方が良いかと思います！

2019-01-08 04:10 UTC, pokotyamu commented on Gemfile
> +  gem 'better_errors'
`better_errors` を入れているのいいですね 👍

2019-01-08 04:10 UTC, pokotyamu commented on app/controllers/users/registrations_controller.rb
> +end
プログラムの最終行には改行を入れましょう！
RubyMine の設定でもあるはずなので、調べてみてください！

[なぜ最終行に改行が必要なのか - komagataのブログ](http://docs.komagata.org/5460)

2019-01-08 04:10 UTC, pokotyamu commented on app/models/user.rb
> +  end
年齢の計算を User モデルに実装しているのいいですね 👍

2019-01-08 04:10 UTC, pokotyamu commented on config/initializers/locale.rb
> +# ロケールを:en以外に変更する
en 以外に変更するというより、`デフォルトのロケールを ja とする` という表現のほうが正確な気がしますね。

2019-01-08 04:10 UTC, pokotyamu commented on app/controllers/users_controller.rb
> +  # before_action :authenticate_user!, only: [:show]
ここ不要なコードはコメントアウトではなく、削除するようにしましょう。
意味なくコメントアウトすると、なにか必要なのかな？という考えを働かせてしまいます 🤔

2019-01-08 04:10 UTC, pokotyamu commented on app/controllers/users_controller.rb
> +    end
うーん 🤔 
ここで誕生日の判定を入れるぐらいなら、作成時点で必須項目にしちゃうかなぁ。
という感想。

2019-01-08 04:10 UTC, pokotyamu commented on app/views/layouts/application.html.haml
> +              %li.nav-item.disabled= link_to 'メール'
まだ実装していないページに関しては、実装するタイミングで追加するというのでいいと思いますよ！
このプルリクエストのタイトルは `ユーザログイン機能、プロフィール編集機能` なので、それに関係することだけに絞るほうがよいと思います！

2019-01-08 04:10 UTC, pokotyamu commented on app/views/layouts/application.html.haml
> +              %li.nav-item.disabled= link_to 'メール'
なので、本当は Bootstrap の導入も別プルリクエストに分けて実装するほうが本当は望ましいです
修正する必要はありませんが 🙏

2019-01-08 07:05 UTC, Terunori commented on .gitignore
> +# End of https://www.gitignore.io/api/rubymine+all
.gitignore_globalに設定し、.gitignoreはFork直後の状態に戻しました。

2019-01-08 07:17 UTC, Terunori commented
ありがとうございます。
レビューをいただくのは初めてなのですが、とても丁寧に見てアドバイスをくださり感激しています。
ご指摘いただいた以下の点を修正しました。

- .gitignore_globalに設定し、.gitignoreはFork直後の状態に戻しました。
- ファイル末尾は改行するようにし、EditorConfigを導入しました。
- 不必要なコメントアウトを削除し一部コメントを修正しました。
- プロフィール編集時、マイページ遷移時のvalidation方法を変更しました。
  - validation用にhelperを作成しました。

コミットの粒度についてまだ慣れないですが考えて実行してみました。
質問なのですが、Push前には $ git rebase -i でコミットをまとめ直したほうが良いのでしょうか。

ブランチ名については後半では適切な名前をつけるようにします。

2019-01-08 07:18 UTC, Terunori commented on app/views/layouts/application.html.haml
> +              %li.nav-item.disabled= link_to 'メール'
わかりました。一旦’メール’へのlinkはコメントアウトしておきます。

2019-01-08 07:18 UTC, Terunori commented on Gemfile
> +# gem 'gretel'
削除しました。

2019-01-08 07:19 UTC, Terunori commented on app/controllers/users/registrations_controller.rb
> +end
ありがとうございます。
調べてみたらRubymineの設定を見つけたので有効にしました。

2019-01-08 07:19 UTC, Terunori commented on config/initializers/locale.rb
> +# ロケールを:en以外に変更する
そうですね、ありがとうございます。

2019-01-08 07:20 UTC, Terunori commented on app/controllers/users_controller.rb
> +  # before_action :authenticate_user!, only: [:show]
わかりました。

2019-01-08 07:22 UTC, Terunori commented on app/controllers/users_controller.rb
> +    end
なるほど、ユーザ登録時点でプロフィールすべて入力しなければならない方法ですね。
ただ、今回は登録時点ではメール、パスワードだけ、あとからプロフィール記入としたかったのでこのようにしました。

2019-01-09 03:54 UTC, pokotyamu commented on app/controllers/users_controller.rb
> +    end
> 今回は登録時点ではメール、パスワードだけ、あとからプロフィール記入としたかったのでこのようにしました。

その意図があるなら良いと思います 👍

2019-01-09 03:57 UTC, pokotyamu commented
> コミットの粒度についてまだ慣れないですが考えて実行してみました。

だいぶいい感じだと思います！

> ファイル末尾改行の調整、rubocop導入

ここはファイル末尾改行の調整と rubocop 導入で分けても良かったですね。
コミットメッセージに複数のことが書かれている場合はあれ？と思うようにするのが良いかと 👍

2019-01-09 04:00 UTC, pokotyamu commented
> 質問なのですが、Push前には $ git rebase -i でコミットをまとめ直したほうが良いのでしょうか。

自分はよくまとめる作業を行いますね！
コミットメッセージを付けなおしたりとかもします。
コマンドライン上ではなくエディタ上や自分のやりやすいやり方でできるように工夫してみるのが良いかと！
自分は Emacs というエディタを使っているので magit 上で git 操作は行うようにしています！

(最高なのは、コミットをまとめたりせず実装段階から分かれているのがいいんですけどね)

2019-01-09 04:01 UTC, pokotyamu approved these changes
LGTM です 👍 
後半に進んでください！

2019-01-09 04:31 UTC, Terunori commented
ありがとうございます。
コミットのまとめ直しにも挑戦してみようと思います。
このプルリクエストはMergeして、新しくbranchを切って進めたらいいですか？

2019-01-10 18:24 UTC, merged