課題後半第1章：自分の面談日程の表示・登録・編集・削除機能
Terunori/e-navigator pull request #2
Opened 2019-02-11 09:50 UTC by Terunori

やりたかったこと
---

- 面接日程の

やったこと
----

- Devise gem の導入
- トップページの追加

動作確認方法
---

- [ ] ユーザーを新規で作成する
- [ ] ユーザーの詳細ページにいく
...

その他
---

2019-02-13 10:03 UTC, pokotyamu commented
👀

2019-02-13 10:06 UTC, pokotyamu commented
コミットの粒度が前より良くなりましたね🤗

ただ、やっぱりまだ複数の作業を１つのコミットにまとめてしまっているところがありますね。
コミットメッセージに `and` が出てきた場合は大体２コミットに分けれる作業をやっている可能性が高いです 👮

2019-02-13 10:34 UTC, pokotyamu requested changes
レビューしました！
少し Rails の基礎的な内容の理解が足りてないような印象を持ちました。
[Rails チュートリアル](https://railstutorial.jp/)をやってみるのはいかがでしょうか？

2019-02-13 10:34 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    p.delete :init
`p` などの一文字の変数名は後から見直した時に分からなくなってしまうので、止めたほうが良いと思います 👮

2019-02-13 10:34 UTC, pokotyamu commented on app/controllers/application_controller.rb
> +  require 'date'
`require 'date'` は必要なんだっけ？ 🤔 
rails の [DateTime](http://railsdoc.com/references/DateTime) だとダメだった感じかな？

2019-02-13 10:34 UTC, pokotyamu commented on app/controllers/application_controller.rb
> +  require 'date'
ApplicationController で require すると継承した全部の Controller に影響してしまうので、使うところだけに絞って限定的にした方が良いと思いました！

2019-02-13 10:34 UTC, pokotyamu commented on app/views/interviews/index.html.haml
> +    - current_user.interviews.includes(:interviewer).each do |intview|
うーん 🤔 
これ view 側で現在のユーザーに紐づく面接一覧を取ってこようとしてますね 👀 
`InterviewsController#index` から渡してあげて、あくまで View は表示に専念する方が良いと思いました！

2019-02-13 10:34 UTC, pokotyamu commented on app/views/interviews/index.html.haml
> +    - current_user.interviews.includes(:interviewer).each do |intview|
bullet 的にも怒られている？

![image](https://user-images.githubusercontent.com/3479317/52705058-5608f080-2fc5-11e9-86fb-5fdea2b104e9.png)

2019-02-13 10:34 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    p.delete :init
ここのコードがどんな意図で実装されているのかが分からない 🤔 
デフォルトの値を設定したいみたいな感じです？

2019-02-13 10:34 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    if @interview.save
`create` した後に `save` を実行しているのは理由ありますか？ 👀

2019-02-13 10:34 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    params.permit(:id, :user_id, :begin_at, :allowed, :interview_id, :init)
ストロングパラメーターいいですね 👍 
ただ、基本的に id に関しては、外部から入力として与えずに、 DB で勝手に割り振られるものとして置いておいたほうが良いので、入力として受け入れないほうがよいと思いました！

2019-02-13 10:34 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    p.delete :init
`init` の存在理由が良くわかってない 🤔

2019-02-13 13:48 UTC, Terunori commented on app/controllers/interviews_controller.rb
> +    p.delete :init
わかりました。ありがとうございます

2019-02-13 13:51 UTC, Terunori commented on app/controllers/application_controller.rb
> +  require 'date'
`Datetime.now`のために必要だと勘違いしていました。除いておきます。

2019-02-13 13:52 UTC, Terunori commented on app/controllers/application_controller.rb
> +  require 'date'
わかりました。

2019-02-13 13:55 UTC, Terunori commented on app/views/interviews/index.html.haml
> +    - current_user.interviews.includes(:interviewer).each do |intview|
これは第2章で他の人の面接一覧を見る画面と変えるのをviewでしようとしたのですが、
たしかにどちらもControllerで処理すべき内容ですね
ありがとうございます。

2019-02-13 14:01 UTC, Terunori commented on app/views/interviews/index.html.haml
> +    - current_user.interviews.includes(:interviewer).each do |intview|
これはまだ他の人に承認/却下の判定を全くもらっていないためすべての`interview`の`interviewer_id`が`nil`になっていて、`interviewer_id`をキーとする`User`の参照が必要ないために起こっている警告です。
`current_user.interviews.includes(:interviewer)`の`includes(:interviewer)`をなくすと、他の人に承認をもらっている面接日程がある場合に`User`を先に読み込んでおくべきという警告が出てしまいます。
もし解決策があれば教えていただけるとありがたいです。

2019-02-13 14:04 UTC, Terunori commented on app/controllers/interviews_controller.rb
> +    p.delete :init
`init`は日程を変更するとき、承認状態と面接官の設定をリセットするかしないかの選択をできるようにするために存在していました

2019-02-13 14:05 UTC, Terunori commented on app/controllers/interviews_controller.rb
> +    p.delete :init
`init`がなくても`allowed = undecided`（承認状態=保留）を直接渡すことで解決しました

2019-02-13 14:07 UTC, Terunori commented on app/controllers/interviews_controller.rb
> +    if @interview.save
すみません。これは勉強不足でした。
`create`に`save`が内包されている(`create=new+save`)んですね。
保存が正しく行われたかどうかで次の表示画面を変えたいため、38行目を`new`に変えておきます。

2019-02-13 14:07 UTC, Terunori commented on app/controllers/interviews_controller.rb
> +    params.permit(:id, :user_id, :begin_at, :allowed, :interview_id, :init)
ありがとうございます。idについてはそのようにします。

2019-02-13 14:39 UTC, Terunori commented
レビューありがとうございます。
Railsの基礎的な内容の理解が足りないということですが、Railsチュートリアルは何度か部分的に参考にしたことがありますが通してやったことは無かったためこの機会に取り組んでみようと思います。

ご指摘いただいた以下の点を修正しました。

- `edit`時のパラメータとして`:init`をやめて、`allowed`を直接コントローラに渡すようにしました
- `create`メソッドで`save`が二回行われていたため`new`に変更しました
- ユーザに紐付けられた面接一覧をコントローラから渡すようにしました
- `require date`を削除しました
- ストロングパラメータから`id`を除外しました

また、面接日程を日付順に並び替えるよう修正しました。
コミットの粒度については、2つ以上のことを思いついても同時にやらないように心がけたいと思います。

bulletから指摘された部分ですが、
まだ他の人に承認/却下の判定を全くもらっていない状態ではすべての`interview`の`interviewer_id`が`nil`になっていて、`interviewer_id`をキーとする`User`の参照が必要ないために`AVOID`という警告がでます。
`current_user.interviews.includes(:interviewer)`の`includes(:interviewer)`を取り除くと、他の人に承認をもらっている面接日程がある場合に`User`を先に読み込んでおくべきという警告（N+1問題）がでます。
承認をもらったあとの読み込みを優先したいため、前者の現在の状態にしています。
もしよりよい解決策があれば教えていただけるとありがたいです。

2019-02-18 10:29 UTC, pokotyamu commented
> 承認をもらっている面接日程がある場合に`User`を先に読み込んでおくべきという警告（N+1問題）がでます。

自分なら、この段階では面接官の概念を登場させない方がいいのではないかな？と思っています。
次節で面接官を依頼するタイミングで、データベースのカラム的にも追加してみたら良かったかも知れませんね！

実際に開発する上では、対象範囲だけにフォーカスして実装するというのも非常に大事になってきます。

2019-02-18 11:07 UTC, pokotyamu requested changes
@Terunori 概ね良くなったと思います！
前回見きれてなかったのですが、外部キー制約の部分が気になったのでコメント付けています 🙏 

また、リファクタリング的にこう書けるよみたいなのも書いてみました！

2019-02-18 11:07 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +  end
```diff --git a/app/controllers/interviews_controller.rb b/app/controllers/interviews_controller.rb
index 20ade79..e63befd 100644
--- a/app/controllers/interviews_controller.rb
+++ b/app/controllers/interviews_controller.rb
@@ -15,11 +15,11 @@ class InterviewsController < ApplicationController
   end

   def update
-    int_params = interview_params.to_h
-    if interview_params[:allowed].to_s == 'undecided'
-      int_params[:interviewer_id] = nil
-    end
-    if @interview.update(int_params)
+    @interview.attributes = interview_params
+    @interview.interviewer_id = nil if interview_params[:allowed] == 'undecided'
+
+    if @interview.save
       redirect_to user_interviews_path
     else
       render 'edit'
```

意図を把握したので、シンプルな実装案を考えてみた。
`#to_h` して無理やりパラメーター側を変えるよりは保存するタイミングを調整してみたらわかりやすいかも知れない！
不要な `#to_s` も消してみました！

2019-02-18 11:07 UTC, pokotyamu commented on app/models/interview.rb
> +  has_one :interviewer, class_name: 'User', foreign_key: :id, primary_key: :interviewer_id
あれ？よく見たら面接官のカラムにも、外部キー制約ついてるのか 👀 
基本的にテーブル構造としては、ユーザーと面接は１対１の関係になっているはずで、その関係を示すのが外部キーであるものなので、 interviewer には外部キーは付けないですね(user_id カラムだけで十分)

この制約があるから `nullify_interviewer ` が必要になった感じかな？

2019-02-18 12:49 UTC, Terunori commented on app/controllers/interviews_controller.rb
> +  end
ありがとうございます。
attributesメソッドとsaveメソッドを用いたやり方はやったことがなかったので勉強になります！
参考にさせていただきます。

2019-02-18 13:53 UTC, Terunori commented on app/models/interview.rb
> +  has_one :interviewer, class_name: 'User', foreign_key: :id, primary_key: :interviewer_id
ここでは

- ユーザ has_many 面接
- 面接 has_one 面接官, class=ユーザ（nilも許可）

というように、
ユーザが子要素として1:多で面接をいくつか持ち、
面接が子要素として1:1で面接官を持つという構造をつくろうとしました。
また、ユーザが削除されたとき

- そのユーザの持つ面接はすべて削除(`dependent: :destroy`)
- そのユーザが面接官となっている面接について面接官および承認状態をもとに戻す

という処理をおこなおうとしました。
なので面接官のカラムにも外部キー制約が必要だと思うのですが、間違っていますか？

対応するコードは以下の部分です。
```ruby
class Interview < ApplicationRecord:
  belongs_to :user
  has_one :interviewer, class_name: 'User', foreign_key: :id, primary_key: :interviewer_id
```
```ruby
class User < ApplicationRecord:
  before_destroy :nullify_interviewer, prepend: true
  has_many :interviews, dependent: :destroy
  belongs_to :interviewer, class_name: 'Interview', foreign_key: :id, optional: true

  private
  def nullify_interviewer
    Interview.where(interviewer_id: self.id).update_all(interviewer_id: nil, allowed: 0)
  end
```

2019-02-19 08:44 UTC, pokotyamu commented on app/models/interview.rb
> +  has_one :interviewer, class_name: 'User', foreign_key: :id, primary_key: :interviewer_id
> * そのユーザの持つ面接はすべて削除(`dependent: :destroy`)
> * そのユーザが面接官となっている面接について面接官および承認状態をもとに戻す

あーそいういことか。
認識としてあっていると思います 🙇 すみません私の理解力が不足していた部分もありました。

ただ、外部キー制約として、 nil を許可するというのを許すというのが個人的に気になってしまいますね 🤔 
これだけで議論がさらに深まりそうなので、フィードバックの時にもう少し話しましょう！

2019-02-19 08:45 UTC, pokotyamu approved these changes
良さそう 👍 
LGTM です！

2019-02-19 11:57 UTC, Terunori commented
ありがとうございます。第二章に進みます。
外部キーについては第二章にも関わりますし、また動作等見ていただけるとありがたいです。

2019-02-19 11:58 UTC, merged