後半第2章 面接官が面談日程を承認 or 拒否するための機能
Terunori/e-navigator pull request #3
Opened 2019-02-20 01:07 UTC by Terunori

やりたかったこと
---

- 第2章第1-3節
- 自分以外のユーザの一覧をトップページに表示する
- 面接官用の面接日程一覧ページを作る
- 面談日程を承認or拒否できるようにする

やったこと
----

- 自分以外のユーザ一覧をトップページに表示した
  - Eメールと名前だけでなく年齢など詳細も表示した
  - 他の人の面接一覧を表示するページへのリンクを追加した
  - 面接官として承認した日程がある場合、そのうち最近のものを表示するようにした
- 面接官用の面接日程一覧ページを作った
  - 承認済み、それ以外で表を分けた（自分の面接日程ページについても同じ）
- 面談日程を承認or却下できるようにした
  - 面接一覧ページでボタンをクリックすることで承認、却下、承認済み日程のキャンセルができるようにした
- ルーティングの見直し
  - 非ログインユーザは面接関連ページを見ることができないように`authenticated`を設定した
  - 非ログイン時とログイン時でルートページを分けた
- ユーザが利用可能なメソッドの指定
  - 面接の新規作成、日程変更、削除は面接者としてログインしたときにしかできないようにした(`InterviewsController`内で設定)
  - 面接の承認と日程変更のメソッドを分け（`update, allow`）別々にストロングパラメータを指定することで意図しない変更を行えないようにした
  - それぞれのストロングパラメータから`user_id`をなくし、`create`するときは`Interview.new`でなく`current_user.interviews.build`で`user_id`を引き継ぐようにした

動作確認方法
---

どうやったらレビュー者が作業内容を確認できるか、確認方法を書いてみましょう。

- [ ] 面接官用ユーザーを新規で作成する
- [ ] プロフィール編集より名前など情報を入力する
- [ ] 面接者用ユーザで日程を新規作成しておく
- [ ] 面接官用ユーザで日程を承認/却下する

その他
---

何か分からない点や、ここ頑張りましたなどあればこちらに書いてください。

2019-02-20 10:25 UTC, pokotyamu requested changes
基本的な流れは良さそう 👌 
ただ、無駄に実行されている `User.find` はまとめるなり、事前にインスタンス変数で結果を保持したものを使うなりした方が良いと思いました！
またルーティングに関してもコメントしています！

2019-02-20 10:25 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    @interviews = User.find(params[:user_id]).interviews.includes(:interviewer).order(begin_at: :asc)
ここ敢えて、２回 `User.find(params[:user_id])` とせずに

```
    @user = User.find(params[:user_id])
    @interviews = @user.interviews.includes(:interviewer).order(begin_at: :asc)
```

で良さそうですね 👀

2019-02-20 10:25 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    @interview = current_user.interviews.build(interview_params)
この `build` メソッドの使い方良いですね 👍 
子リソースの作成時には良くやるので積極的に使っていきましょう 👍

2019-02-20 10:25 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +  end
```
def set_user
  @user = User.find(params[:user_id])
end

def correct_user
  redirect_to user_interviews_path if current_user != @user
end
```

のようなメソッドを用意しておき、 `before_action` で事前によんであげることで、更にシンプルかつ複数箇所での `User.find(params[:user_id])` を防げそうですね 👀

2019-02-20 10:25 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +  def others_interview_params
ここのパラメーターが意味するところとしては `承認` のためのパラメーターとするほうが名前としてより具体的で適切な気がします！

2019-02-20 10:25 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +  def others_interview_params
よくやるのは、アクション名に対応した形で、命名する方法ですかね。

`update_params` と `create_params` 等。

2019-02-20 10:25 UTC, pokotyamu commented on config/routes.rb
> +      patch 'users/update_profile', to: 'users/registrations#update_profile', as: 'update_profile'
ルーティングこのままでもいいとは思いますが、一応。
基本的に REST の考えに則って path は設定すべきです。

- `users` に対する `get` なら一覧
- `users` に対する `post` なら作成
- `users/:id` に対する `get` なら詳細
- `users/:id` に対する `put` or `patch` なら更新
- `users/:id` に対する `delete` なら削除

といったように。

2019-02-20 10:25 UTC, pokotyamu commented on config/routes.rb
> +      patch 'users/update_profile', to: 'users/registrations#update_profile', as: 'update_profile'
なので、 `edit_` や `update_` は、ほんとに必要なのか？というのが疑問として残ります 🤔

2019-02-20 10:25 UTC, pokotyamu commented on config/routes.rb
> +      patch 'users/update_profile', to: 'users/registrations#update_profile', as: 'update_profile'
設定より規約が優先される のが Rails の特徴なので、あまり独自でパスを定義する `get` や `patch` などは多用せずに、 `resource` や `resources` で出来る範囲でやるというのが良いと思います！

2019-02-20 13:59 UTC, Terunori commented on config/routes.rb
> +      patch 'users/update_profile', to: 'users/registrations#update_profile', as: 'update_profile'
ルーティングについてコメントありがとうございます。
課題前半で`devise`gemを用いた際に、`devise`により自動で作成されるルーティングに対し、ユーザの詳細を編集したり更新したりするルートをどのように設定したら良いか悩んだ結果現在のルート設定を実装しました。

方針を確認してから修正したいのですが、`routes.rb`を修正するときに

```ruby
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root :to => 'users#index'
      delete 'logout', to: 'devise/sessions#destroy'
      resources :users, only: [:index, :show, :edit, :update] do
        resources :interviews do
          member do
            patch :allow, as: 'allow'
          end
        end
      end
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end
end
```

のようにして、

- `UserController#show`でマイページ（自分のプロフィール情報）を表示
- `UserController#edit`で自分のプロフィール情報を編集できる画面を表示
- `UserController#update`で自分のプロフィール情報を更新

するようにし、これらのメソッドは`user_id`が`current_user.id`に一致する場合のみ実行できるようにするのが良いということでしょうか。

2019-02-20 13:59 UTC, Terunori commented on app/controllers/interviews_controller.rb
> +  def others_interview_params
パラメータの命名について教えていただきありがとうございます。修正します。

2019-02-20 14:00 UTC, Terunori commented on app/controllers/interviews_controller.rb
> +    @interview = current_user.interviews.build(interview_params)
ありがとうございます！

2019-02-20 14:00 UTC, Terunori commented on app/controllers/interviews_controller.rb
> +  end
ありがとうございます。
こちらの方法を採らせていただきます。
DRYな実装ができるようがんばります！

2019-02-21 10:17 UTC, pokotyamu commented on config/routes.rb
> +      patch 'users/update_profile', to: 'users/registrations#update_profile', as: 'update_profile'
うん！いい感じだと思いますね！
resources がしっかり使えてていいと思いました 👍

2019-02-21 16:53 UTC, Terunori commented
以下の内容を更新しました

- `InterviewsController`で複数存在した`User.find`を`set_user`メソッドにまとめた
- パラメータの名前をより適切なものに変更
- ユーザの詳細、編集、更新のルーティングの改善

確認お願いします！

2019-02-22 01:28 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    set_user
自分なら、 `before_action` で `set_user` を事前に行う用に実装するかな。
`correct_user` の関心事は、本人かどうかの確認だし、インスタンス変数からセットすることは役割では無さそう 👀

2019-02-22 01:53 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +  end
> `create_interview_params`, `update_interview_params`, `allow_interview_params`

`InterviewsController` 内で受け付けたパラメーターだし、 `create_params`  でも十分意味は通りそうな気がしました！

2019-02-22 01:53 UTC, pokotyamu commented on app/controllers/users_controller.rb
> +  def update_user_params
https://github.com/Terunori/e-navigator/pull/3/files#r259188121
同様

2019-02-22 01:55 UTC, pokotyamu commented
@Terunori 名前つけと、コールバック関数化した方が良いかなと思うところにコメントしておきました 🙋‍♂️

2019-02-22 04:25 UTC, Terunori commented
パラメータの名付け方と、`set_user`を事前におこなうように修正しました
ご確認お願いします

2019-02-22 10:16 UTC, pokotyamu commented
動作的にも、良さそうに思います 👌 
マージして次に進んでください！！！

2019-02-22 10:21 UTC, Terunori commented
ありがとうございます。
第3章に進みます！

2019-02-22 10:21 UTC, merged