後半第3章 面談日程を知らせるためのメール送信機能
Terunori/e-navigator pull request #4
Opened 2019-02-27 02:07 UTC by Terunori

やりたかったこと
---
- ユーザーを指定して申請をすると、指定したユーザーに希望する面談日程の承認を依頼するメール
- 承認した後に、両者に面接日が決ったことを伝えるメール

やったこと
----

- gmailで新規にメールアドレスを取得し, 2段階認証を設定することでアプリパスワードを入手した
- `.env`で環境変数を設定した
- `development`環境でメール設定を追加した
- `InterviewMailer`を新規作成した
- 面接希望日程を決めた後に、面接官に承認依頼するメールを送信するようにした（`InterviewMailer#request_schedule_email`）
- 面接官が承認する日程を決定した後に、面接者に承認した日時を伝えるメールを送信できるようにした（`InterviewMailer#apply_schedule_email`）
- Herokuに環境変数を設定し`production`環境にもメール設定を追加した

動作確認方法
---

どうやったらレビュー者が作業内容を確認できるか、確認方法を書いてみましょう。
例)

- [ ] 存在するメールアドレスを持つユーザーを２つ作成し一方でログインする
- [ ] プロフィール編集よりプロフィールを設定する
- [ ] 面接一覧で新規に日程を作成して、送り先のメールアドレスを選択してメール送信ボタンをクリックする
- [ ] 承認依頼メールが送り主、送り先それぞれで受信できているか確認する
- [ ] ログアウトし、もう一方のアカウントでログインする
- [ ] 相手（面接者）の面接一覧ページより日程の承認をおこなう
- [ ] 「承認した日程をメールで通知する」ボタンをクリックすることで、承認状態を面接者に伝えることができる
- [ ] 日程決定メールが送り主、送り先それぞれで受信できているか確認する

その他
---

2019-03-01 02:25 UTC, pokotyamu requested changes
主にメソッド名を中心にレビューしました！
内容に疑問があれば再度質問よろしくおねがいします！

2019-03-01 02:25 UTC, pokotyamu commented on app/mailers/interview_mailer.rb
> +class InterviewMailer < ApplicationMailer
面接に関するメールが `InterviewMailer` なのすごく良いですね 👍

2019-03-01 02:25 UTC, pokotyamu commented on app/mailers/interview_mailer.rb
> +  def request_schedule_email(send_to, cc)
Mailer なので、 `_email` というサフィックスはいらないかなと思います！

2019-03-01 02:25 UTC, pokotyamu commented on app/mailers/interview_mailer.rb
> +    @interviewee = cc
自分なら、ここ `#apply_schedule_email` 同様に引数名揃えるな 🤔

2019-03-01 02:25 UTC, pokotyamu commented on app/mailers/interview_mailer.rb
> +    @interview_schedules = @interviewee.interviews.where(allowed: 'allowed', interviewer_id: @interviewer.id).order(begin_at: :asc)
ちなみに、 enum のヘルパーメソッドも使えますよ〜

`@interviewee.interviews.allowed` で `allowed` な状態のものだけ取得することができます 👍

2019-03-01 02:25 UTC, pokotyamu commented on app/models/user.rb
> +    return unless birthday
nil ガードすごく良いですね 👍

2019-03-01 02:25 UTC, pokotyamu commented on app/models/user.rb
> +    self.name.present? ? self.name : self.email
`name_email` ってメソッド名から何が期待されているのかが読み取れなかった 🤔

2019-03-01 02:25 UTC, pokotyamu commented on app/views/interview_mailer/apply_schedule_email.html.haml
> +  =render :partial => 'signature'
`partial` 使ってシグネチャー付けるの良いですね 👍

2019-03-01 02:25 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +  def apply_request
あーなるほど、承認後にこのボタンを押すことで通知というフローなのか 🤔 
これこのボタンを押し忘れたら、メールが送られない気がするので機能としてちょっとむずかしいですね 🤔 

承認ボタンが押されたタイミングでメールを通知するようにするのはどうでしょうか？ 😄

2019-03-01 02:25 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +  def notify_request
アクション名と中身があっていないような気がします。
面接の申請をするのが `apply` ではないかな？ 🤔

2019-03-02 06:59 UTC, Terunori commented on app/mailers/interview_mailer.rb
> +  def request_schedule_email(send_to, cc)
了解です！

2019-03-02 07:00 UTC, Terunori commented on app/mailers/interview_mailer.rb
> +    @interviewee = cc
そうですね、直します

2019-03-02 07:00 UTC, Terunori commented on app/mailers/interview_mailer.rb
> +    @interview_schedules = @interviewee.interviews.where(allowed: 'allowed', interviewer_id: @interviewer.id).order(begin_at: :asc)
なるほど、便利です
教えてくださりありがとうございます！

2019-03-02 07:01 UTC, Terunori commented on app/models/user.rb
> +    self.name.present? ? self.name : self.email
メソッド名再考します

2019-03-02 07:03 UTC, Terunori commented on app/controllers/interviews_controller.rb
> +  def apply_request
わかりました
面接希望日程に対する「承認」、「キャンセル」ボタンが押されたタイミングでメール送信が行われるよう修正します

2019-03-02 07:03 UTC, Terunori commented on app/controllers/interviews_controller.rb
> +  def notify_request
再考してみます

2019-03-02 07:12 UTC, Terunori commented on app/controllers/interviews_controller.rb
> +  def notify_request
今回自分でも適切な名前つけに悩んで、結果混乱してミスしてました
修正時にもう一度1から考えます
ご指摘ありがとうございます

2019-03-04 02:02 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +  def notify_request
名前つけすごく難しいですよね 😓 
そのメソッドやクラスがどんな役割を果たすのか？みたいな視点で考えるといいと思います！

基本的にメソッドは動詞にすると綺麗にハマると思います！

2019-03-04 07:40 UTC, Terunori commented on app/models/user.rb
> +    self.name.present? ? self.name : self.email
名前があれば名前、そうでなければメールアドレスを返すので、
name_or_email
としました

2019-03-04 07:40 UTC, Terunori commented on app/controllers/interviews_controller.rb
> +  def notify_request
アドバイスありがとうございます

2019-03-04 09:50 UTC, Terunori commented
以下のように修正しました

- メールに関する引数の名前変更
  - `interviewer, interviewee`に統一した
- 承認、キャンセルはボタンが押されたときにメール通知を送信するように変更
  - `InterviewMailer.allow_schedule`, `InterviewMailer.cancel_schedule` 
- 承認、キャンセル、却下について確認のポップアップを出すように変更
- 承認申請メールの名前変更
  - `request`は既にActionMailerで予約済みなので`request_approval`とした
- `User.name_email`を`User.name_or_email`に名前変更した
- メール文面のURLからの遷移をスムーズにするために、ログインした後、ログイン前に開こうとしていたページに飛ぶように変更

ご確認よろしくお願い致します

2019-03-05 07:14 UTC, pokotyamu commented
> 作業の途中でgit rebase -iする前にgithubにpushしてしまったので一度force-pushしました

rebase でコミット整えているんですね！！！すごい！！！！
コメントが崩れるので、 `force-push` は気をつけたほうが良いですが、積極的に練習されてて良いなと思いました 👍

2019-03-05 07:18 UTC, pokotyamu approved these changes
修正内容確認して良さそうに思いました！！

自分としてのコメントは残してみましたが、修正するかはおまかせします 🙏 

この内容でも LGTM ですので e-Navigator 完走です！！！！
お疲れ様でした 🎉 🎉 🎉

2019-03-05 07:18 UTC, pokotyamu commented on app/models/user.rb
> +    self.name.present? ? self.name : self.email
> 名前があれば名前、そうでなければメールアドレスを返す

メソッドがやりたいこととしては、そうなんだろうけどその振る舞いって結局何がしたいのかな？というのが今回のポイントかなと思いました。

コードを読む限り、メールなどで登場するユーザーの名前という認識なので、自分だったら、 `screen_name` とかって付けるかなと思いました！

---

別件で、ここまで悩む必要があるなら要件をわかりやすくする意味でも、名前必須とかにしちゃうというアプローチもあると思います！

2019-03-05 12:52 UTC, Terunori commented
ありがとうございます。
そうですね、面接登録前にプロフィール入力必須にする、という方が実際良かったかなと振り返って思います。
完走ということでMergeします！本当にありがとうございました。

2019-03-05 12:52 UTC, merged